# frozen_string_literal: true

# add linux platform with: BUNDLE_GEMFILE=ruby-3-0.gemfile bundle lock --add-platform x86_64-linux

source "https://rubygems.org"

# specify ruby version
ruby '~> 2.6.0'

# Specify your gem's dependencies in encoded_token.gemspec
gemspec :path => '../..'

gem "rake"
gem "rspec"
gem 'simplecov'
gem 'simplecov-cobertura'
gem 'sdoc'
gem 'puma'
gem 'rubocop'

