
name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
        include:
          - ruby: "2.5"
            gemfile: "ruby-2-5"
          - ruby: "2.6"
            gemfile: "ruby-2-6"
          - ruby: "2.7"
            gemfile: "ruby-2-7"
          - ruby: "3.0"
            gemfile: "ruby-3-0"
          - ruby: "3.1"
            gemfile: "ruby-3-1"
          - ruby: "3.2"
            gemfile: "ruby-3-2"
          - ruby: "3.3"
            gemfile: "ruby-3-3"
          - ruby: "3.4"
            gemfile: "ruby-3-4"
          
    runs-on: ubuntu-latest

    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}/Gemfile
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }} 
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Bundle
        run: bundle install
        
      - name: Run tests
        run: bundle exec rake

